# Generated by Django 3.2.2 on 2021-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Etudiant', 'Etudiant')], max_length=50, null=True),
        ),
    ]
