# Generated by Django 3.2.2 on 2021-05-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Use',
        ),
    ]
