# Generated by Django 3.2.2 on 2021-05-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210528_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='use',
            name='idC',
        ),
        migrations.DeleteModel(
            name='Conseiller',
        ),
    ]
