# Generated by Django 3.2.2 on 2021-05-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210528_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('CNE', models.CharField(max_length=50, null=True, unique=True)),
                ('phone', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='use',
            name='idC',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='idC', to='account.conseiller'),
        ),
    ]
