# Generated by Django 3.2.2 on 2021-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210528_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conseiller',
            name='CNE',
        ),
        migrations.AddField(
            model_name='conseiller',
            name='cne',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
