# Generated by Django 3.2.2 on 2021-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210528_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('cne', models.CharField(max_length=50, null=True, unique=True)),
                ('phone', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
