# Generated by Django 3.2.2 on 2021-05-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_conseiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='idC',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='idC', to='account.conseiller'),
        ),
    ]
