# Generated by Django 3.2.2 on 2021-05-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20210528_1439'),
        ('account', '0012_use_idc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='use',
            name='idC',
        ),
        migrations.DeleteModel(
            name='Conseiller',
        ),
        migrations.DeleteModel(
            name='Use',
        ),
    ]
