# Generated by Django 3.2.2 on 2021-05-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_auto_20210528_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('cne', models.CharField(max_length=50, null=True, unique=True)),
                ('phone', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('cne', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Particulier', 'Particulier'), ('Etudiant', 'Etudiant')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True, unique=True)),
                ('solde', models.FloatField(null=True)),
                ('age', models.IntegerField()),
                ('idC', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='idC', to='account.conseiller')),
            ],
        ),
    ]
