# Generated by Django 3.2.2 on 2021-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210528_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseille',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
