# Generated by Django 3.2.2 on 2021-05-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_address_use_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conseille',
            old_name='cne',
            new_name='cni',
        ),
    ]
