# Generated by Django 3.2.2 on 2021-05-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_cne_conseille_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='idC',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idC', to='account.conseille'),
        ),
    ]
