# Generated by Django 3.2.2 on 2021-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_use_idc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='cne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='use',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
