# Generated by Django 3.2.2 on 2021-05-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20210528_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='dotationE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='dotationT',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
