# Generated by Django 3.2.2 on 2021-05-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210528_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='dotationE',
            field=models.CharField(default='Bloquer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='use',
            name='dotationT',
            field=models.CharField(default='Bloquer', max_length=50, null=True),
        ),
    ]
