# Generated by Django 3.2.2 on 2021-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20210528_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='cheque',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
