# Generated by Django 3.2.2 on 2021-05-29 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_use_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, null=True)),
                ('idU', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='idU', to='account.use')),
            ],
        ),
    ]
