# Generated by Django 3.2.2 on 2021-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_blockchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='chain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='unconfirmed_transactions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
