# Generated by Django 3.2.2 on 2021-05-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210530_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='text',
        ),
    ]
