# Generated by Django 3.2.2 on 2021-05-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_blockchain_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='blockchain',
            name='unconfirmed_transactions',
        ),
    ]
