# Generated by Django 3.2.2 on 2021-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20210530_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='chain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
