# Generated by Django 3.2.2 on 2021-05-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_blockchain_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
    ]
