# Generated by Django 3.2.2 on 2021-05-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20210530_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
