# Generated by Django 3.2.2 on 2021-05-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_b_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='use',
            name='cheque',
        ),
        migrations.AddField(
            model_name='use',
            name='Adate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
