# Generated by Django 3.2.2 on 2021-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_reclamation_adate'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='cheque',
            field=models.CharField(default='non', max_length=50, null=True),
        ),
    ]
