# Generated by Django 3.2.2 on 2021-05-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_user_use'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='idD',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='idD', to='account.use'),
        ),
        migrations.AddField(
            model_name='operation',
            name='idR',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='idR', to='account.use'),
        ),
    ]
