# Generated by Django 3.2.2 on 2021-05-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20210516_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=50, null=True),
        ),
    ]
