# Generated by Django 3.2.2 on 2021-05-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='idD',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='idR',
        ),
    ]
