# Generated by Django 3.2.2 on 2021-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20210529_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
