# Generated by Django 3.2.2 on 2021-05-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_operation_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='telephobe',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
