# Generated by Django 3.2.2 on 2021-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_operation_telephobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='Adate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
